# Generated by Django 2.2 on 2020-11-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bottle_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='用户名', max_length=128)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(default='昵称', max_length=128)),
                ('sex', models.CharField(choices=[('0', '男'), ('1', '女')], max_length=32)),
                ('description', models.TextField(default='简介', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='bottles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='漂流瓶内容', max_length=128)),
                ('reply', models.TextField(blank=True, max_length=128)),
            ],
        ),
    ]
