# Generated by Django 2.2 on 2020-11-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybottles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottles',
            name='owner',
            field=models.CharField(default='扔瓶子的人', max_length=128),
        ),
    ]
