# Generated by Django 2.2 on 2020-11-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybottles', '0002_bottles_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottles',
            name='replier',
            field=models.CharField(default='回复瓶子的人', max_length=128),
        ),
    ]
