# Generated by Django 2.2 on 2020-11-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybottles', '0005_emailverifyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle_user',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
    ]
