# Generated by Django 2.2 on 2020-11-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybottles', '0007_auto_20201107_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle_user',
            name='description',
            field=models.TextField(default='简介', max_length=100, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='bottle_user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='bottle_user',
            name='is_active',
            field=models.IntegerField(default=1, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='bottle_user',
            name='name',
            field=models.CharField(default='昵称', max_length=128, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='bottle_user',
            name='password',
            field=models.CharField(max_length=256, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='bottle_user',
            name='sex',
            field=models.CharField(choices=[('0', '男'), ('1', '女')], max_length=32, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='bottle_user',
            name='username',
            field=models.CharField(default='用户名', max_length=128, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='bottles',
            name='replier',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
