# Generated by Django 2.2 on 2020-11-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybottles', '0010_bottle_user_is_replied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottle_user',
            name='is_replied',
        ),
        migrations.AddField(
            model_name='bottles',
            name='is_replied',
            field=models.IntegerField(default=1, verbose_name='是否被回复'),
        ),
    ]
