# Generated by Django 2.2 on 2020-11-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybottles', '0011_auto_20201112_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottles',
            name='is_replied',
            field=models.IntegerField(default=0, verbose_name='是否被回复'),
        ),
    ]
