# Generated by Django 2.2 on 2020-11-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybottles', '0012_auto_20201113_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle_user',
            name='sex',
            field=models.IntegerField(choices=[('1', '男'), ('0', '女')], max_length=32, verbose_name='性别'),
        ),
    ]
