# Generated by Django 2.2 on 2020-11-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybottles', '0013_auto_20201114_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle_user',
            name='sex',
            field=models.IntegerField(choices=[('1', '男'), ('0', '女')], verbose_name='性别'),
        ),
    ]
